// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backdrop': string;
  'beerForm': string;
}
declare var cssExports: CssExports;
export = cssExports;
