// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'grabbing': string;
  'placeholder': string;
  'slider': string;
  'slider-wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
