// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'divider': string;
  'policy': string;
  'promotions': string;
  'register-form': string;
}
declare var cssExports: CssExports;
export = cssExports;
