// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'after-register-modal': string;
  'description': string;
  'divider': string;
}
declare var cssExports: CssExports;
export = cssExports;
