// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkbox': string;
  'checked': string;
}
declare var cssExports: CssExports;
export = cssExports;
