// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'rotated': string;
  'scroller': string;
}
declare var cssExports: CssExports;
export = cssExports;
