// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'jumbo': string;
  'paragraphs': string;
}
declare var cssExports: CssExports;
export = cssExports;
