// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'images': string;
  'meetings': string;
  'more': string;
  'size1': string;
  'size2': string;
}
declare var cssExports: CssExports;
export = cssExports;
