// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'marker': string;
  'section-name': string;
  'section-name__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
