// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'beer': string;
  'content': string;
  'description': string;
  'details': string;
  'kind': string;
  'name': string;
  'operations': string;
  'sub-name-type': string;
}
declare var cssExports: CssExports;
export = cssExports;
