// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'close': string;
  'dialog__overlay': string;
}
declare var cssExports: CssExports;
export = cssExports;
