// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'close-icon': string;
  'modal-content': string;
  'modal-wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
