// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'beer-name-rate': string;
  'personality': string;
  'profile': string;
  'tile': string;
  'users': string;
}
declare var cssExports: CssExports;
export = cssExports;
