// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'animate-beer-content': string;
  'animate-bubble': string;
  'animate-foam': string;
  'bubble': string;
  'fade-in': string;
  'foam': string;
  'glass': string;
  'handle': string;
  'loader': string;
  'loader-overlayed': string;
  'overlay-in': string;
}
declare var cssExports: CssExports;
export = cssExports;
