// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'aside-wrapper': string;
  'content': string;
  'copyright': string;
  'divider': string;
  'links': string;
  'logo': string;
}
declare var cssExports: CssExports;
export = cssExports;
