// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'btn-animated-background': string;
  'btn-circled': string;
  'btn-default': string;
  'btn-outlined-red-white': string;
}
declare var cssExports: CssExports;
export = cssExports;
