// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form-field': string;
  'icon': string;
  'input-wrapper': string;
  'invalid': string;
  'overlay': string;
  'title': string;
  'validation-message': string;
}
declare var cssExports: CssExports;
export = cssExports;
