// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottom-content': string;
  'content': string;
  'description': string;
  'email-input': string;
  'footer': string;
  'links': string;
  'navigate': string;
  'title': string;
  'we-started': string;
}
declare var cssExports: CssExports;
export = cssExports;
