// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alert': string;
  'alert-animated-in': string;
  'alert-animated-in-out': string;
  'alert-animated-out': string;
  'alert-error': string;
}
declare var cssExports: CssExports;
export = cssExports;
