// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'logo': string;
  'logo--default': string;
  'logo--light': string;
  'name': string;
}
declare var cssExports: CssExports;
export = cssExports;
