// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'beer__placeholder': string;
  'beers': string;
  'loadMoreButton': string;
}
declare var cssExports: CssExports;
export = cssExports;
