// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'jumbo': string;
  'jumbo__text': string;
  'perf-flex': string;
}
declare var cssExports: CssExports;
export = cssExports;
