// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'beers-users': string;
  'dark-bg': string;
  'home': string;
  'light-bg-1': string;
  'light-bg-2': string;
  'section-name-2': string;
  'section-name-3': string;
  'section-name-4': string;
}
declare var cssExports: CssExports;
export = cssExports;
