// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons-container': string;
  'container': string;
  'forgot-password': string;
}
declare var cssExports: CssExports;
export = cssExports;
