// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'divider': string;
  'link--hover': string;
  'links': string;
  'navbar': string;
}
declare var cssExports: CssExports;
export = cssExports;
